services:
  backend:
    build: 
      context: ../..
      dockerfile: docker/dev/Dockerfile
      target: builder  # Stop at builder stage for tests
    ports:
      - "5000:5000"
    volumes:
      - ../../data:/app/data
      - pytest_cache:/app/.pytest_cache  # Cache between runs
    environment:
      - STORAGE_FILE=/app/data/checks.json
      - FLASK_ENV=development
      - CHECK_INTERVAL=60
    hostname: backend  # Explicit hostname  
    networks:
      - health-net

  checker:
    build:
      context: ../..
      dockerfile: docker/dev/Dockerfile
      target: builder
    container_name: health-check-checker
    command: ["python", "-m", "app.checker"]
    volumes:
      - ../../data:/app/data
    environment:
      - STORAGE_FILE=/app/data/checks.json
      - FLASK_ENV=development
      - CHECK_INTERVAL=60
    depends_on:
      - backend
    networks:
      - health-net

  frontend:
    build:
      context: ../../ui
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - health-net    

networks:
  health-net:
    driver: bridge

volumes:
  data:
  pytest_cache: