services:
  web:
    image: ${DOCKER_HUB_USERNAME}/devops-health-check:${TAG:-latest}
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - data:/app/data
      - pytest_cache:/app/.pytest_cache  # Cache between runs
    environment:
      - FLASK_ENV=production
      - STORAGE_FILE=/app/data/checks.json
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 10s
      timeout: 2s
      retries: 3
      start_period: 30s      


  checker:
    image: ${DOCKER_HUB_USERNAME}/devops-health-check:${TAG:-latest}
    command: ["python", "-m", "app.checker"]
    restart: unless-stopped
    volumes:
      - data:/app/data
    depends_on:
      web:
        condition: service_healthy

volumes:
  data:
  pytest_cache: