name: CI Test Mode
on: workflow_dispatch

jobs:
  dry-run:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This is a test - no actual deployment"
      - run: echo "Branch: ${{ github.ref }}"